language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./mvnw clean"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - psd1390@gmail.com